### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by DominiqueMakowski** [RealityBending/IllusionGameSelfAssociation#3]
not a priority for now but just for reference:

- [x] Split the tasks into 3 subfolders (questionnaires, self-task, illusions), and have a main index files at the root from which we can access any one of them (similarly to the structure in the IG repos), will make it easier to modify and check each components, and then in the end we can assemble the 3 components back into one experiment.
- [x] Self task: remove the completion bar during the experiment
- [x] Self task: perhaps during the instructions that says "You are the triangle, Friend is the circle etc." show the shapes too to have improve the visual association

@anshu-97

**Comment by DominiqueMakowski** [comment]
Currently there seem to be a bug as all the responses "L" are classified as correct.

**Comment by DominiqueMakowski** [comment]
just checked that awesome job thanks @anshu-97 🙏
